# Generated by Django 4.0.1 on 2022-02-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Post',
        ),
    ]
