# Generated by Django 4.0.1 on 2022-02-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_follow_follower_follow_followers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Follower',
        ),
    ]
